@startuml
Actor user
user -> rslv: pid_str
activate rslv
rslv -> splitter: [1] ]pid_str
note over splitter: Split string to components\nfor matching a definition.
splitter -> rslv: parsed_pid
rslv -> definitions: match(parsed_pid)
definitions --> definitions: reconcile_synonyms()
definitions -> rslv: pid_definition
rslv -> rslv: matched_pid(parsed_pid, pid_definition)
rslv -> user: action(matched_pid)
note right: action() may be redirect\n to target or return metadata.
deactivate rslv
@enduml
