# This workflow will install Python dependencies, run tests and build

name: Python package

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"
        enable-cache: true
        cache-dependency-glob: uv.lock
        python-version: 3.10
        activate-environment: true
      
    - name: Install dependencies
      run: |
        uv pip install --upgrade pip
        uv pip install pytest
    - name: Test with pytest
      run: |
        uv run pytest
    - name: Build wheel
      run: uv build

